\documentclass[a4paper,8pt]{extarticle}
\usepackage[a4paper,top=3cm,bottom=2cm,left=2cm,right=2cm,marginparwidth=1.75cm]{geometry}
\usepackage[english]{babel}  % force American English hyphenation patterns
\usepackage[utf8]{inputenc}  % unicode
% \usepackage{lipsum}  % generate text
\usepackage{hyperref}  % have nice references, I use it especially for urls.
\usepackage{todonotes} % to be able to add corrections, todos, comments
\usepackage[color]{changebar}  % todonotes: to be able to add corrections
\cbcolor{red} % todonotes: color of the changebar
\definecolor{lgray}{gray}{0.95}
\usepackage[nottoc,notlot,notlof]{tocbibind} % makes bibliography appear in toc
\usepackage{listings}  % include code
\lstset{basicstyle=\ttfamily, breaklines = true, backgroundcolor=\color{lgray},language=bash,basicstyle=\ttfamily,columns=fullflexible} % listings: code style
\usepackage{wrapfig}  % figures can be wrapped in text
\usepackage{mathtools}  % have math symbols
\usepackage{amsmath}  % math stuff
\usepackage{amssymb}  % math stuff
\usepackage{booktabs}  % to make professional tables
% ------------------------------------------------------------------------- glossary
\usepackage[acronym,nomain]{glossaries} % ABBREVIATIONS
% Acronym definitions , use e.g. \gls{pca} to use a defined acronym
\newacronym[first={\textit{Petunia exserta}}]{pex}{\textit{P. exserta}}{\textit{Petunia exserta}}
% ------------------------------------------------------------------------- document descriptions
\title{Knitr template}
\author{Noëlle Schenk}
\date{2018-03-15}
% ------------------------------------------------------------------------- literature references
\usepackage[backend=biber]{biblatex} % to use biber for my citations
\addbibresource{references.bib} % where latex can find the .bib file
% -------------------------------------------------------------------------
\begin{document}
\maketitle
\tableofcontents
\newpage

\section{some examples}
A path can be included like this : \path{home/user/knitr} \\
include a word from the glossary the first time \gls{pex} and the second time \gls{pex}. 

\lstinline!ls -l | grep 'useful'! to include an inline code. \\
code can be included like this as well : \texttt{listings}, but this does not allow for special symbols like \_ . (Unless you escape them, of corse) \\ 

\begin{figure}
  \caption{\label{fig:sample} A nice sample picture.}
  \centering
    \includegraphics[width=0.2\textwidth]{sample.png}
\end{figure}
For references : see Figure \ref{fig:sample}. 

\begin{table}
\caption{\textbf{Nice table.} Check out booktabs for more inspiring table styles or the presentation of Markus P\" uschel \href{https://www.inf.ethz.ch/personal/markusp/teaching/guides/guide-tables.pdf}{small Guide to Making Nice Tables}.}
\centering
\begin{tabular}{@{}lll@{}}\toprule 
\toprule
\textbf{RIL7} (f7)&  \textbf{exserta} (ex) &  \textbf{axillaris} (ax)\\
\midrule
plate 2 : 8 reads, data NA & plate 1 : 1 & plate 1 : 2 \\			
plate 3 : 94 reads & plate 3 : 1 & plate 2 : 1\\
plate 4 : 93 reads & plate 4 : 1 & \\
\midrule
187 & 3 & 3 \\
f7.platex.y.q30l50.sam & ex.platex.y.q30l50.sam & ax.platex.y.q30l50.sam \\
f7.platex.y.jobnumber.out .err & ex.platex.y.jobnumber.out  .err & ax.platex.y.jobnumber.out .err \\
\midrule
\multicolumn{3}{l}{TOTAL 193 samples}\\
\multicolumn{3}{l}{reads at \path{/home/user/results}} \\
\bottomrule
\end{tabular}	
\label{table:readstoref}
\end{table}

\section{another section}
\begin{table}
\caption{\textbf{minor allele frequencies} genolike\_test.mafs.gz output file}	
\centering
\begin{tabular}{@{}lllllll@{}}\toprule 
\toprule
chromo	& position	& major	& minor	& unknownEM	& pu-EM	& nInd	\\
Peex113Ctg00003	& 28382	& T	& C	& 0.097175	& 0.0000001997185	& 6	\\
Peex113Ctg00004	& 118715	& A	& G	& 0.003254	& 0.00000000004385381	& 181	\\
Peex113Ctg00004	& 119009	& A	& G	& 0.333003	& 0	& 178	\\
Peex113Ctg00016	& 11831	& T	& C	& 0.016492	& 0.0000000003690032	& 12	\\
Peex113Ctg00016	& 11870	& T	& A	& 0.107668	& 0	& 4	\\
Peex113Ctg00016	& 11878	& A	& G	& 0.147158	& 0	& 9	\\
Peex113Ctg00016	& 11914	& C	& T	& 0.163204	& 0	& 9	\\
Peex113Ctg00016	& 11924	& G	& T	& 0.147181	& 0	& 9	\\
Peex113Ctg00016	& 11925	& G	& T	& 0.147206	& 0	& 9	\\
Peex113Ctg00016	& 57577	& A	& G	& 0.094229	& 0	& 8	\\
Peex113Ctg00016	& 57585	& G	& A	& 0.094234	& 0	& 8	\\
Peex113Ctg00016	& 57587	& T	& G	& 0.094228	& 0	& 8	\\
\bottomrule	
\end{tabular}	
\label{table:maf.gz}
\end{table}

\paragraph{make nice paragraps : } That works like this. By the way, referring to a table also works, see Table \ref{table:readstoref}. \\

Citing a paper works like this: \cite{nielsen2011} \\

\todo[inline,color=green!40]{Do you need to have a colorful bar in your text? This todo can be seen at the end of the file again} 
\todo[inline]{That's the default color for todonotes inline todos. Check out the todonotes package for more nice things.}

<<>>=
# Ever heard about Phred quality score? No? This is how it works:
error = seq(0,1,0.01)
Qphred = -10*log10(error)
@

<<phred, fig.pos="ht", fig.width=3, fig.height=3, fig.cap="Phred quality score",out.width='.4\\linewidth'>>=
plot(error, Qphred, xlab='Error probability per base call')
@

See Figure \ref{fig:phred} for phred. A knitr inline works like this : $\Sexpr{seq(0,1,0.5)}$

\begin{lstlisting}[caption={from single\_ job.sh, running a program with some settings},label={lst:angsd}]
#!/bin/sh
# -GL 2 : use GATK , -doGlf 2 : output beagle file

# note : Elapsed Time = 01:03:32 of 04:00:00
\end{lstlisting}
I can also include an output from the terminal as a listing. That looks like this:
\begin{lstlisting}[caption={beagle likelihood file}]
marker	allele1	allele2	Ind0	Ind0	Ind0
1_14000202	2	0	0.000532	0.999468	0.000000
1_14000873	2	0	0.000000	0.030324	0.969676
1_14001018	3	1	0.000000	0.015429	0.984571
1_14001867	0	2	0.000056	0.333333	0.666611
1_14002342	1	3	0.941072	0.058928	0.000000
1_14002422	0	3	0.000000	0.111147	0.888853
1_14002474	3	1	0.969662	0.030338	0.000000
1_14003581	1	3	0.000000	0.200027	0.799973
1_14004623	3	1	0.000000	0.200035	0.799965
\end{lstlisting}
By the way, see listings \ref{lst:angsd} to show you how to refer to listings.


\fbox{\parbox{\textwidth}{\textit{THEORY} --- \textbf{a topic} --- \\
here I include some theory about a topic. Or use the box for any other purpose.
}}

\begin{lstlisting}
# wondering how to run a .Rnw document from terminal?
cd ~/wherethedocumentis/template_knitr.Rnw
Rscript -e "library(knitr); knit('template_knitr.Rnw')"  # makes you a .tex file from the R code chunks.
pdflatex template_knitr.tex
pdflatex template_knitr.tex
biber template_knitr  # to have references and bibliography correctly
pdflatex template_knitr
# if you use ubuntu, you can open the pdf with:
gnome-open template_knitr.pdf
\end{lstlisting}

\section{Glossary}
\printglossaries

\printbibliography

\listoftodos % include the todos at the end of document
\end{document}
